#!/bin/bash
echo "🚀 Optimizing for_sale table structure..."
echo ""
echo "This script will:"
echo "✅ Convert images column from TEXT to JSONB for better performance"
echo "✅ Add missing columns (title, description, agent fields)"
echo "✅ Create optimized indexes for fast queries"
echo "✅ Set up proper RLS policies"
echo "✅ Add data validation constraints"
echo ""
echo "⚠️  This is a safe migration that preserves existing data"
echo ""

# Execute the optimization script
echo "📝 Executing optimization SQL..."
echo ""
echo "Execute the following SQL manually or via your Supabase migration tool:"
echo "=========================================="
cat supabase/database/tables/optimize_for_sale_table.sql
echo "=========================================="
echo ""
echo "✅ Optimization script ready!"
echo ""
echo "💡 Benefits of this optimization:"
echo "   • JSONB images column for better performance and querying"
echo "   • Comprehensive indexing for fast searches"
echo "   • Proper data validation and constraints"
echo "   • Optimized RLS policies for security"
echo "   • Denormalized location data for performance"

