// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydphzcwssycpkkoqttau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkcGh6Y3dzc3ljcGtrb3F0dGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTMyNDQsImV4cCI6MjA2MDU4OTI0NH0.sI-E9WVFNyl79AxhqCdzDG_bjEKcRDxtW-_3bcuq-Hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});